services:
  etl:
    build: .

  db:
    image: postgres:alpine
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
